spec:
  structures:
    - content_blocks
  label: Induvidual Product
  description: Induvidual Product section
  icon: "lock"
  tags: ["induvdual product"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Induvidual Product
  description: Product
  induvidual_product:
    - title:
      image:
        image_path:
        image_alt:
  
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}